#!/bin/sh
# gen-assets.sh — bake a source-tree asset folder into a generated C header as
# byte arrays + a {path,bytes,len} lookup table. Part of the openq embedded
# web-assets pipeline: src/qlang/html/ is the source of truth, this bakes it
# into the binary (served by q_http.c when no on-disk ./html docroot exists).
# Byte arrays (not string literals) so binary assets (.ico) embed losslessly.
# DO NOT edit the generated output — edit the folder and rebuild.
#
# Usage: gen-assets.sh <output.h> <asset-root-dir>
# Deterministic: files walked in LC_ALL=C sorted order; only relative paths and
# a FIXED banner are embedded (never $root or a timestamp) — a second run is
# byte-identical. Written atomically (temp + cmp + mv): the output mtime only
# changes when the content changes, so a Makefile FORCE-run does not needlessly
# rebuild dependents, and a failed run never leaves a half-written header.
# Portable: POSIX sh + od + awk + wc; runs on the BUILD host.
set -eu

out=$1
root=$2
guard=OPENQ_HTML_ASSETS_GEN_H
tmp="$out.tmp.$$"

# Sorted relative paths of every regular file under $root (deterministic order).
files=$(cd "$root" && find . -type f | LC_ALL=C sort | sed 's|^\./||')
[ -n "$files" ] || { echo "gen-assets: no files under $root" >&2; exit 1; }

# Asset-name grammar: segments of [A-Za-z0-9._-] joined by '/'. Rejects anything
# that could break/inject the generated C string literal (quotes, backslash,
# control bytes, newlines, spaces) or the newline-delimited walk. Fail LOUD.
printf '%s\n' "$files" | while IFS= read -r f; do
    case "$f" in
        *[!A-Za-z0-9._/-]*|/*|*//*|*/) echo "gen-assets: unsafe asset path: $f" >&2; exit 1 ;;
    esac
done

{
    printf '/* AUTO-GENERATED by tools/gen-assets.sh from the asset folder — DO NOT EDIT. */\n'
    printf '#ifndef %s\n#define %s\n' "$guard" "$guard"
    printf '#include <stddef.h>\n\n'

    # Pass 1: one byte array per file (trailing 0x00 sentinel, NOT counted in len
    # — it just keeps a 0-byte file's array non-empty and NUL-terminates text).
    idx=0
    printf '%s\n' "$files" | while IFS= read -r f; do
        printf 'static const unsigned char asset_%d[] = {\n' "$idx"
        od -A n -v -t x1 "$root/$f" | awk '
            { for (i = 1; i <= NF; i++) {
                  printf "0x%s,", $i; if (++c % 16 == 0) printf "\n" } }'
        printf '0x00\n};\n'
        idx=$((idx + 1))
    done

    # Pass 2: the lookup table (relative path, bytes, byte length via wc -c).
    printf '\nstatic const struct { const char* path; const unsigned char* bytes; size_t len; }\n'
    printf 'q_html_assets[] = {\n'
    idx=0
    printf '%s\n' "$files" | while IFS= read -r f; do
        n=$(wc -c < "$root/$f")
        printf '    { "%s", asset_%d, %s },\n' "$f" "$idx" "$n"
        idx=$((idx + 1))
    done
    printf '};\n'

    count=$(printf '%s\n' "$files" | wc -l | tr -d ' ')
    printf 'static const size_t q_html_assets_count = %s;\n' "$count"
    printf '#endif /* %s */\n' "$guard"
} > "$tmp"

# Atomic replace: only touch $out (and its mtime) when the content changed.
if [ -f "$out" ] && cmp -s "$tmp" "$out"; then
    rm -f "$tmp"
else
    mv -f "$tmp" "$out"
fi
